#ifndef __OPLUS_CHG_SYMBOL_H__
#define __OPLUS_CHG_SYMBOL_H__

#if IS_ENABLED(CONFIG_OPLUS_SM8350_CHARGER) || IS_ENABLED(CONFIG_OPLUS_SM8450_CHARGER)
#if IS_ENABLED(CONFIG_OPLUS_ADSP_CHARGER)
#define USE_ADSP
#endif
#endif

#endif /* __OPLUS_CHG_SYMBOL_H__ */